apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-streams-hpa
  namespace: streamspace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-streams-app
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
