apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: streamspace
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
    scrape_configs:
      - job_name: 'kafka-streams'
        static_configs:
          - targets: ['kafka-streams-service.streamspace.svc.cluster.local:8080']
